spring.application.name=backend
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d8nnpb8js32c73dt7ov0-a.oregon-postgres.render.com:5432/searchsphere_gh4q
spring.datasource.username=postgres_user
spring.datasource.password=44tdGRbxm26ZgAcROr8yj4hZABzWoUof

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=SearchSphere-Super-Secret-JWT-Key-2024-Min32Chars!
jwt.expiration=86400000

# MongoDB Atlas — REPLACE <YOUR_PASSWORD> with your actual Atlas password
spring.data.mongodb.uri=mongodb+srv://root:Root1234@cluster0.gefxlwr.mongodb.net/searchsphere_logs?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=searchsphere_logs
